// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEIwcgEJSvlrcLIfRCZKFP1KXvtr0bo8',
    appId: '1:1071859697836:web:2165d6995036c8bea77709',
    messagingSenderId: '1071859697836',
    projectId: 'fir-app-e9bd5',
    authDomain: 'fir-app-e9bd5.firebaseapp.com',
    storageBucket: 'fir-app-e9bd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dlLfu2wzphRWkKbjJ-9sIsj7OsaLv8U',
    appId: '1:1071859697836:android:bb2f1423600d8103a77709',
    messagingSenderId: '1071859697836',
    projectId: 'fir-app-e9bd5',
    storageBucket: 'fir-app-e9bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0W9_xhKrmXImLPFXaOBaMQl6FdiZVNZo',
    appId: '1:1071859697836:ios:b4562b48f12d33aca77709',
    messagingSenderId: '1071859697836',
    projectId: 'fir-app-e9bd5',
    storageBucket: 'fir-app-e9bd5.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0W9_xhKrmXImLPFXaOBaMQl6FdiZVNZo',
    appId: '1:1071859697836:ios:823f9ef9cc95628ba77709',
    messagingSenderId: '1071859697836',
    projectId: 'fir-app-e9bd5',
    storageBucket: 'fir-app-e9bd5.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
